env: "local"
storage:
  type: "postgres"
  host: 192.168.31.6
  port: 5433
  user: "postgres"
  password: "1234"
  database: "urlshortdb"
  sslmode: "disable"
http_server:
  address: "localhost:8081"
  timeout: 4s # время на  чтение запроса и такое же время на отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
